[default]
log_level = "normal"
limits = {"file/avif" = "1Mib", "file/gif" = "1Mib", "file/jpg" = "1Mib", "file/jpeg" = "1Mib", "file/png" = "1Mib", "file/svg" = "1Mib", "file/webp" = "1Mib", "file/webm" = "64Mib", "file/mp4" = "64Mib", "file/mpeg4" = "64Mib", "file/mpg" = "64Mib", "file/mpeg" = "64Mib", "file/mov" = "64Mib"}
cli_colors = false
template_dir = "src/views"
temp_dir = "/tmp"

[default.databases.main_connection]
url = "postgres://postgres:mysecretpassword@127.0.0.1:5432/postgres"